#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

namespace think;

// 加载基础文件
use app\index\utility\Cache\UserCache;

require __DIR__ . '/thinkphp/base.php';

// 执行应用
Container::get('app', [__DIR__ . '/application/'])->initialize();

//\think\facade\Cache::set('userCache',new UserCache());
//\think\facade\Cache::set('userCache')->userTable = '111';
\think\facade\Cache::clear();
Console::init();