<?php
namespace app\index\facade;

use think\Facade;

class TestIndexFacade extends Facade
{
    public static function getFacadeClass()
    {
//        parent::getFacadeClass(); // TODO: Change the autogenerated stub

        return 'app\index\controller\Index';
    }
}